version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-insidejwt'
    environment:
      - 'POSTGRES_USER=grig'
      - 'POSTGRES_HOST_AUTH_METHOD=true'
      - 'POSTGRES_DB=lessons'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8090:8090